### PR TITLE
Added Autoupdating Pokemon Map

### PR DESCRIPTION
**Pull request by TheZ3ro**
Added Auto-Updating Pokemon Map (need a webserver like SimpleHTTPServer running)
Added option to Hide Pokemon on the Map
Edited the README.md

Screen https://imgur.com/VBodsvU

### CODE REVIEW

**Comment by MonsterMMORPG** [comment]
so awesome please add this too

**Comment by qdlmcfresh** [comment]
Slight suggestion. For me it looks like this http://image.prntscr.com/image/3f4b130846824b97b03809bc1475c05c.png
I think it would be better to circle around the given location instead of wandering away from it in one direction. But maybe thats just me. Great work btw!

**Comment by TheZ3ro** [comment]
@qdlmcfresh Yes, I know this "problem" but it's due to @leegao implementation of Cell-scanning.
Maybe in future we can move the location around in the map and get info on that cell. That would be great! :icecream:

**Comment by ArchdukeTim** [comment]
I'm getting api request errors and InsecureRequestWarnings. I got past the request errors once but then I got an index out of range on line 301 I believe?.

**Comment by TheZ3ro** [comment]
@Twinters007 the InsecureRequestWarnings can be fixed by uncommenting line 13-14 in main.py (my fault)

For the index out of range, are you using Google or PTC for Authentication?

TODO:
- Change location from the Map (Start scanning from that new location)
- Scan for Gyms and PokeStops

**Comment by ArchdukeTim** [comment]
I'm using my pokemon trainer log in

**Comment by MonsterMMORPG** [comment]
@TheZ3ro  can you check whether the searching algorithm can be improved or not? i am running 3 instances and nothing worthy appears in my city :(

**Comment by Simon0x** [comment]
nice to see this pull request.
think this is a good work. ^^

**Comment by TheZ3ro** [comment]
@Twinters007 @MonsterMMORPG  the server are online when you try to login?

**Comment by MonsterMMORPG** [comment]
@TheZ3ro right now it works

**Pull request closed without merging**
